// Generated by tools/find_training_recipes.cjs; source puzzles remain in puzzles.js.
const SUDOKU_TRAINING_RECIPES = {
  "nakedSingle": [
    {
      "id": "0000183b305c",
      "step": 0
    },
    {
      "id": "0001d5d6314e",
      "step": 0
    },
    {
      "id": "000212406270",
      "step": 7
    },
    {
      "id": "00023580f347",
      "step": 0
    }
  ],
  "hiddenSingle": [
    {
      "id": "000212406270",
      "step": 0
    },
    {
      "id": "00031006ebf1",
      "step": 4
    },
    {
      "id": "0003af4e2943",
      "step": 0
    },
    {
      "id": "0004125f628d",
      "step": 16
    }
  ],
  "pointing": [
    {
      "id": "0000847b216e",
      "step": 28
    },
    {
      "id": "00010f10503b",
      "step": 13
    },
    {
      "id": "00024d60bdaf",
      "step": 19
    },
    {
      "id": "000293df085f",
      "step": 19
    }
  ],
  "claiming": [
    {
      "id": "00057aae90e4",
      "step": 17
    },
    {
      "id": "00065780345c",
      "step": 29
    },
    {
      "id": "000aab8430c0",
      "step": 16
    },
    {
      "id": "001cf1a97192",
      "step": 15
    }
  ],
  "nakedPair": [
    {
      "id": "0002a00dec12",
      "step": 13
    },
    {
      "id": "00065780345c",
      "step": 30
    },
    {
      "id": "000e01eedac3",
      "step": 27
    },
    {
      "id": "0019cf830635",
      "step": 13
    }
  ],
  "hiddenPair": [
    {
      "id": "0019cf830635",
      "step": 15
    },
    {
      "id": "00005f662e09",
      "step": 21
    },
    {
      "id": "00009e4900fa",
      "step": 13
    },
    {
      "id": "0000b2c3fc62",
      "step": 10
    }
  ],
  "nakedTriple": [
    {
      "id": "00023f11679e",
      "step": 21
    },
    {
      "id": "0004176c8af1",
      "step": 8
    },
    {
      "id": "0004d93c5158",
      "step": 24
    },
    {
      "id": "000530e59ae0",
      "step": 19
    }
  ],
  "xWing": [
    {
      "id": "00013f7e562a",
      "step": 18
    },
    {
      "id": "000160237251",
      "step": 15
    },
    {
      "id": "0001767b888a",
      "step": 25
    },
    {
      "id": "00026b82b6d3",
      "step": 10
    }
  ],
  "swordfish": [
    {
      "id": "0001767b888a",
      "step": 26
    },
    {
      "id": "0004d93c5158",
      "step": 26
    },
    {
      "id": "000c97d948f0",
      "step": 28
    },
    {
      "id": "000cf9265b56",
      "step": 14
    }
  ],
  "xyWing": [
    {
      "id": "0000b2c3fc62",
      "step": 11
    },
    {
      "id": "00013f7e562a",
      "step": 19
    },
    {
      "id": "000175e5f83b",
      "step": 31
    },
    {
      "id": "0001767b888a",
      "step": 27
    }
  ]
};
if (typeof module !== 'undefined' && module.exports) module.exports = SUDOKU_TRAINING_RECIPES;
